config/routes.rb
Starscream::Application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :users
  resources :supervisors

  resources :dashboards, :only => [:index]

  resources :accounts
  resources :periods
  resources :reviews
  resources :goals
  resources :progresses

  get 'pricing' => 'static#pricing', :as => :static_pricing
  get 'features' => 'static#features', :as => :static_features

  resources :dashboards, :only => [:index]

  root :to => 'home#index'

end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :account
  has_many :reviews
  has_many :users, :through => :reviews

  before_create :check_active
  after_create :change_period_state
  after_update :close_reviews

  validates :account_id, :name, :start_date, :end_date, :presence => true

  state_machine :initial => :unregistered do
    event :opener do
      transition :unregistered => :open
    end

    event :close do
      transition :open => :closed
    end
  end

  attr_accessible :account_id, :end_date, :name, :start_date, :state

  private

  def check_active
    account.periods.find_by_state("open").nil? ? true : false
  end

  def change_period_state
    p = self
    p.opener

    users = User.find(:all, :conditions => { :account_id => p.account_id })

    users.each do |user|
      review = Review.find(:all, :conditions => { :state => "open", :user_id => user.id }).count

      if review > 0
        return
      else
        review = Review.create(:account_id => p.account_id,
                                :period_id => p.id,
                                :user_id => user.id)
      end
    end
  end

  def close_reviews
    p = self
    if p.state == "closed"
      #close all reviews for this period
      reviews = Review.find(:all, :conditions => { :period_id => self })

      reviews.each do |review|
        review.closer
      end

      #then create a default period and reviews for all users
      period = Period.create(:name => "**Default Period**",
                           :start_date => Date.today,
                           :end_date => Date.today,
                           :account_id => self.account_id)
    end
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @periods = Period.where(:account_id => current_user.account_id)
    @period_default = Period.find(:all, :conditions => { :account_id => current_user.account_id, :state => "open", :name => "**Default Period**" }).count
  end

  def show
    @period = Period.find(params[:id])
  end

  def new
    @period = Period.new
  end

  def create
    @period = Period.new(params[:period])
    @period.account_id = current_user.account_id
    if @period.save
      flash[:notice] = "Period created"
      redirect_to dashboards_path
    else
      # format.html { render action: "new" }
      redirect_to periods_path, alert: 'Unable to create new Period. An *OPEN* Period still exist'
    end
  end

  def edit
    @period = Period.find(params[:id])
  end

  def update
    @period = Period.find(params[:id])
    if @period.update_attributes(params[:period])
      flash[:notice] = "Successfully updated period."
      redirect_to periods_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @period = Period.find(params[:id])
    @period.destroy
    flash[:notice] = "Successfully destroyed period."
    redirect_to periods_url
  end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= simple_form_for(@period, :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="inputs">
    <%= f.input :name, :placeholder => 'period name',:required => true, :autofocus => true %>
    <%= f.input :start_date, :placeholder => 'dd/mm/yyyy', :as => :date_picker, :required => true %>
    <%= f.input :end_date, :placeholder => 'dd/mm/yyyy', :as => :date_picker, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dashboards_path, :class => 'btn' %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<br>
<div class="container">
  <h1>Edit Performance Review Period</h1><br>

  <%= simple_form_for(@period, :html => { :class => 'form-horizontal' }) do |f| %>
    <div class="inputs">
      <%= f.input :name, :required => true, :autofocus => true %>
      <%= f.input :start_date, :as => :date_picker, :required => true %>
      <%= f.input :end_date, :as => :date_picker, :required => true %>

      <%= f.input :state, :as => :radio_buttons, :required => true, :collection => [ "open", "closed" ] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  users_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/periods/index.html.erb
<br>
<div class="container">
  <% if @period_default > 0 %>
    <div class="alert">
      <p>A default <strong>'Performance Review Period'</strong>has been created. Please change the 'Performance Review Period' name before you continue!</p>
    </div>
  <% end %>

  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="periods">
    <thead>
      <tr>
        <th>Period Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>State</th>
        <th class="td-actions">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @periods.each do |period| %>
        <tr>
          <td><%= link_to period.name, period_path(period) %></td>
          <td><%= period.start_date %></td>
          <td><%= period.end_date %></td>
          <td><%= period.state %></td>
          <td class="td-actions">
            <%= link_to "Edit", edit_period_path(period), :class => 'btn btn-mini' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/periods/new.html.erb
<div class="container">
  <h1>Create Performance Review Period</h1><br>

  <%= render :partial => 'form' %>
</div>