config/routes.rb
Starscream::Application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :users
  resources :supervisors

  resources :dashboards, :only => [:index]

  resources :accounts
  resources :periods
  resources :reviews
  resources :goals
  resources :progresses

  get 'pricing' => 'static#pricing', :as => :static_pricing
  get 'features' => 'static#features', :as => :static_features

  resources :dashboards, :only => [:index]

  root :to => 'home#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  has_one :progress, :dependent => :destroy

  validates :title, :start_date, :due_date, :presence => true

  after_create :change_goal_state

  state_machine :initial => :unregistered do
    event :opener do
      transition :unregistered => :open
    end

    event :closer do
      transition :open => :closed
    end
  end

  attr_accessible :description, :due_date, :review_id, :start_date, :state, :title, :user_id

  private

  def change_goal_state
    self.opener
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @review = Review.find_by_user_id(current_user, :conditions => { :state => "open" }).id.to_i
    @goal = current_user.goals.build(params[:goal])
    @goal.review_id = @review
    @progress = @goal.build_progress(params[:progress])
    @progress.user_id = @goal.user_id
    if @goal.save
      flash[:notice] = "Goal created"
      redirect_to dashboards_path
    else
      render 'new'
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(params[:goal])
      flash[:notice] = "Successfully updated goal."
      redirect_to goals_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    flash[:notice] = "Successfully destroyed goal."
    redirect_to goals_url
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for(@goal, :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="inputs">
    <%= f.input :title, :required => true, :autofocus => true, 
                :placeholder => "add your goal title here", :input_html => { :class => "span5" } %>
    <%= f.input :description, :as => :text, :required => true, 
                :placeholder => "add your goal description here (not more than 255 characters)", :input_html => { :class => "span5" } %>
    <%= f.input :start_date, :as => :date_picker, :required => true %>
    <%= f.input :due_date, :as => :date_picker, :required => true %>
  </div>
  
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dashboards_path, :class => 'btn' %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>
<%= render :partial => 'form' %>

app/views/goals/index.html.erb
<div class="container">
	<div class="widget widget-table action-table">
		<div class="widget-header">
			<i class="icon-th-list"></i>
			<h3>My Goals</h3>
		</div> <!-- /widget-header -->

		<div class="widget-content">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Goal</th>
		        <th>% Complete</th>
		        <th>Status</th>
			      <th>Start Date</th>
			      <th>Due Date</th>
						<th class="td-actions">Action</th>
					</tr>
				</thead>
				<tbody>
	        <% @goals.each do |goal| %>
					  <tr>
					    <td>
		            <strong><%= link_to goal.title, goal_path(goal) %></strong><br>
		            <p><%= truncate goal.description, length: 50 %></p>
		        </td>
		        <td><%= number_to_percentage(goal.progress.percent_complete, :precision => 0) %></td>
		        <td><%= goal.progress.state %></td>
			      <td><%=l goal.start_date %></td>
			      <td><%=l goal.due_date %></td>
						  <td class="td-actions">
							  <%= link_to "Edit", edit_goal_path(goal), :class => 'btn btn-mini btn-success' %><br>
		            <%= link_to 'Progress', edit_progress_path(goal.progress), :class => 'btn btn-mini btn-warning' %><br>
		            <%= link_to 'Delete', goal, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %>
						  </td>
					  </tr>
					<% end %>
	      </tbody>
	    </table>

	    <div class="form-actions">
	      <%= link_to "Add New Goal", new_goal_path, :class => 'btn btn-primary' %>
	    </div>
		</div> <!-- /widget-content -->
	</div> <!-- /widget -->
</div>

app/views/goals/new.html.erb
<h1>Create Goal</h1>
<%= render :partial => 'form' %>